[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[functions]]
  directory = "netlify/functions"

[[scheduled.functions]]
  name = "fetchNews"
  cron = "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"

[[scheduled.functions]]
  name = "fetchRFPs"
  cron = "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"

[[scheduled.functions]]
  name = "fetchJobs"
  cron = "0 0,2,4,6,8,10,12,14,16,18,20,22 * * *"

[[scheduled.functions]]
  name = "recomputeScores"
  cron = "0 2 * * *"

[[scheduled.functions]]
  name = "sendDigest"
  cron = "15 8 * * *"
